### ISSUE TITLE
To-do for finishing report

### ISSUE THREAD

**Issue by Rohan-Dayal01** [shanko07/ml4fg#5]
- [x] Discuss architecture for neural network and recurrent neural network in the methodology section (Stephen)
- [x] Discuss how hyperparameters were chosen for the regression models (Rohan)
- [x] Clarify in introduction how we are using variety of methods (Rohan)
- [x] Clarify that our project is focusing on general healthy vs disease state cells and not necessarily just Leukemia vs healthy in the introduction section(Rohan)
- [x] Edit methodology section to remove old figures and writing about LSTM and GRU (Rohan)
- [ ] Build summary table and write about how we assess the performance of the models in the results section (i.e. why the findings are important and why they may have come out the way they did) (Kyle)
- [ ] Include methodology section for SVM and XGBoost if we are including them (Kyle)
- [ ] Discussion section (all three of us)
